name: Update BTC Trading Signals

on:
  schedule:
    - cron: '0 14 * * *'  # Runs every day at 2 PM UTC
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  run-signals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("DBI", repos = "https://cloud.r-project.org")'
          Rscript -e 'install.packages("RSQLite", repos = "https://cloud.r-project.org")'
          Rscript -e 'install.packages("dplyr", repos = "https://cloud.r-project.org")'
          Rscript -e 'install.packages("lubridate", repos = "https://cloud.r-project.org")'
          Rscript -e 'install.packages("TTR", repos = "https://cloud.r-project.org")'
          Rscript -e 'install.packages("purrr", repos = "https://cloud.r-project.org")'
          Rscript -e 'install.packages("zoo", repos = "https://cloud.r-project.org")'

      - name: Run Signals.R
        run: Rscript R/Signals.R


